First pass rough draft of Queue excercise
devleague/js-queue pull request #1
Opened 2016-12-09 02:29 UTC by TheWhiteOx

w00t

2016-12-12 20:55 UTC, theRemix requested changes

2016-12-12 20:55 UTC, theRemix commented on README.md
> +We will be creating a **module** that helps us generate a **Queue**. A queue is a data structure in which the first element is inserted from one end called REAR (also called tail), and the deletion o
explicitly say that the goal is to create an **es6 Class** to be run in the node environment

2016-12-12 21:01 UTC, theRemix requested changes
queue datastructure is not a stack

2016-12-12 21:01 UTC, theRemix commented on lib/Queue.js
> + *
describe that there should be a constructor method, and the constructor arguments (_none_)

2016-12-12 21:01 UTC, theRemix commented on lib/Queue.js
> + * Queue a stack data structure.
"Queue data structure"

_a Queue is not a Stack_

2016-12-12 21:01 UTC, theRemix commented on lib/Queue.js
> + * Queue => Stack
"Queue Class"

_a Queue is not a Stack_

2016-12-12 21:08 UTC, theRemix requested changes

2016-12-12 21:08 UTC, theRemix commented on package.json
> +    "test": "mocha --watch"
add a `bail` flag

2016-12-12 21:12 UTC, theRemix requested changes
enqueue

2016-12-12 21:12 UTC, theRemix commented on lib/Queue.js
> +   * @param item
describe what enqueue should return (nothing? or new _size?)

2016-12-12 21:17 UTC, theRemix requested changes
readme updates

2016-12-12 21:17 UTC, theRemix commented on README.md
> +
Explain that they should will be using an anonymous `Object` as an internal datastore type, cannot use `Array`.

2016-12-12 21:17 UTC, theRemix commented on README.md
> +# The Queue Datastructure
"Data Structure"
two words

2016-12-12 21:28 UTC, sgnl commented on test/test.js
> +  describe('Queue behavior', function() {
Currently with this title the output is:

`1) Queue Queue behavior A new queue should start with a size of 0:`

consider removing "Queue" from this describe block so the output is instead:

`1) Queue behavior A new queue should start with a size of 0:`

2016-12-12 21:28 UTC, sgnl commented on README.md
> +### push(item)
`push` should be `enqueue` instead?

2016-12-12 21:28 UTC, sgnl commented on README.md
> +### pop()
`pop` should be `dequeue` instead?

2016-12-12 21:55 UTC, theRemix requested changes
is there a way to redefine the instructions such that a student can implement Queue in other ways?

consider these two branches
**remix_complete_1**
https://github.com/theRemix/js-queue/blob/remix_complete_1/lib/Queue.js
passes all tests using the names and implementation details defined exactly as the comments suggest. (how you probably solved it too)

**remix_complete_2**
https://github.com/theRemix/js-queue/blob/remix_complete_2/lib/Queue.js
passes all tests using a different implementation, i updated the comments describe the new version.

2016-12-12 21:55 UTC, theRemix commented on lib/Queue.js
> + * @private {number} _end                  Default value should be set 0.
definition to allow different implementation types

2016-12-12 22:07 UTC, ghost commented on test/test.js
> +    });
What should the `peak` method return if there are 0 items in the queue? I'm thinking a return value of `null` would be good. thoughts?

2016-12-16 16:01 UTC, theRemix commented on test/test.js
> +    });
i think `null` would be good.

2016-12-17 03:04 UTC, TheWhiteOx commented on README.md
> +We will be creating a **module** that helps us generate a **Queue**. A queue is a data structure in which the first element is inserted from one end called REAR (also called tail), and the deletion o
✅

2016-12-17 03:04 UTC, TheWhiteOx commented on lib/Queue.js
> + * Queue => Stack
✅

2016-12-17 03:04 UTC, TheWhiteOx commented on lib/Queue.js
> + * Queue a stack data structure.
✅

2016-12-17 03:05 UTC, TheWhiteOx commented on lib/Queue.js
> + *
✅

2016-12-17 03:05 UTC, TheWhiteOx commented on package.json
> +    "test": "mocha --watch"
✅

2016-12-17 03:06 UTC, TheWhiteOx commented on lib/Queue.js
> +   * @param item
good point, having it return new size

2016-12-17 03:06 UTC, TheWhiteOx commented on README.md
> +# The Queue Datastructure
✅

2016-12-17 03:07 UTC, TheWhiteOx commented on README.md
> +
✅

2016-12-17 03:11 UTC, TheWhiteOx commented on test/test.js
> +  describe('Queue behavior', function() {
✅

2016-12-17 03:11 UTC, TheWhiteOx commented on README.md
> +### push(item)
✅

2016-12-17 03:12 UTC, TheWhiteOx commented on README.md
> +### pop()
✅

2016-12-17 03:14 UTC, TheWhiteOx commented on test/test.js
> +    });
✅

2016-12-17 03:25 UTC, TheWhiteOx commented on lib/Queue.js
> + * @private {number} _end                  Default value should be set 0.
Cool second implementation! Updated the exercise prompt to say that the datastore object is optional and there is a way to finish the exercise without it.

2018-01-17 03:38 UTC, merged